### ISSUE TITLE
UserContext may call a warning

### ISSUE THREAD

**Issue by ppxb** [flatlogic/react-material-admin#14]
in function loginUser if you write like this

```js
if (!!username && !!password) {
    setTimeout(() => {
      localStorage.setItem('id_token', 1)
      dispatch({ type: 'LOGIN_SUCCESS' })
      setError(null)
      setIsLoading(false)

      histroy.push('/app/dashboard')
    }, 2000)
}
```
may call a warning likes `Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.`

but write like this 

```js
if (!!username && !!password) {
    setTimeout(() => {
      localStorage.setItem('id_token', 1)
      setError(null)
      setIsLoading(false)
      dispatch({ type: 'LOGIN_SUCCESS' })
    
      histroy.push('/app/dashboard')
    }, 2000)
```

it will not.

**Comment by michaeldaineka** [comment]
Hi there!

Thanks for your help!

We've already pushed a commit that contains your implementation of the React error message
