### ISSUE TITLE
Sign up form errors

### ISSUE THREAD

**Issue by jarkin13** [flatlogic/react-material-admin#20]
1. Email address is incorrectly spelt
<img width="438" alt="Screen Shot 2020-02-07 at 3 21 45 PM" src="https://user-images.githubusercontent.com/4195698/74070178-9a9f5000-49bd-11ea-9219-88143e2b1cba.png">
2. Full name input field has a `type="email"` rather than `type="text"`
<img width="395" alt="Screen Shot 2020-02-07 at 3 23 41 PM" src="https://user-images.githubusercontent.com/4195698/74070256-d76b4700-49bd-11ea-84fb-a801662087e3.png">

**Comment by michaeldaineka** [comment]
Hi

Thank you for the feedback!

We've already fixed that issues

Best regards
