### ISSUE TITLE
Dot component style not being applied

### ISSUE THREAD

**Issue by Soremwar** [flatlogic/react-material-admin#23]
Apparently, the dotSmall style is never being created to begin with in the `<Dot />` component.

![Styles](https://user-images.githubusercontent.com/42647963/76691853-7585a900-661d-11ea-9674-be6d291e9928.png)

![Component](https://user-images.githubusercontent.com/42647963/76691860-83d3c500-661d-11ea-85da-b8d45f04e820.png)

Works as it is though

**Comment by michaeldaineka** [comment]
Hi

Thank you for the feedback!

![image](https://user-images.githubusercontent.com/43149862/76963499-2ba90580-6932-11ea-8d1b-1dfbf2613f0e.png)

We've fixed the problem.

Best regards
