### ISSUE TITLE
Beautiful UI and awsome job 

### ISSUE THREAD

**Issue by Johnny00520** [flatlogic/react-material-admin#24]
I do have a quick question. When I try to run and test the UI myself, I got the warning. 

> Warning: React.createFactory() is deprecated and will be removed in a future major release. Consider using JSX or use React.createElement() directly instead.

I don't see anywhere in the codebase that has createFactory(). Do you know where that might be? 

And seems like the library `recharts` has many warnings

**Comment by michaeldaineka** [comment]
Hi @Johnny00520.

Thanks you!

BTW why you need to use ```createFactory```?
