### ISSUE TITLE
component .scss files are not taking precedence over .css file imported in index.js file

### ISSUE THREAD

**Issue by sushmitg** [flatlogic/react-material-admin#31]
I installed node-sass and then bootstrap and imported bootstrap.css file in index.js file. Now I have a component which is importing it's own .scss file in it, which overrides some bootstrap classes. but the override is not working, when i inspected i found that the bootstrap's <style> comes after the component's <style> in the chrome's dev inspector.

As per the docs of create-react-app the component's .css/.scss should take the precedence over the .css imported in index.js file.

**Comment by michaeldaineka** [comment]
Hi, @sushmitg.

Material UI comes with the bootstrap stylesheet inside. You don't need to manual include this in index.js file.

But if you wanna add this, you need to add scss support to CRA, and override bootstrap classes in  your components via ```:global``` scoping.
